# Generated by Django 3.2.6 on 2021-08-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_datetime',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
