# Generated by Django 3.2.6 on 2021-08-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='listings',
        ),
    ]
